// src/main/java/com/katorymnd/pawapay/sdk/utils/license/LicenseValidator.java
package com.katorymnd.pawapay.sdk.utils.license;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Core license validation
 */
public class LicenseValidator {

    private static final Logger LOGGER = LoggerFactory.getLogger(LicenseValidator.class);
    
    // Regex matches formats like: PYTHON-PREMIUM-9EC3-3F9B-C513
    private static final Pattern LICENSE_PATTERN = Pattern.compile("^[A-Z]+-[A-Z]+-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$");

    // Singleton instance (replaces the global "validator = LicenseValidator()" from Python)
    private static final LicenseValidator INSTANCE = new LicenseValidator();

    @SuppressWarnings("unused")
    private final Map<String, Object> validatedLicenses;
    
    @SuppressWarnings("unused")
    private long lastCheck;

    private LicenseValidator() {
        this.validatedLicenses = new HashMap<>();
        this.lastCheck = 0;
    }

    /**
     * Get the singleton instance of the LicenseValidator
     */
    public static LicenseValidator getInstance() {
        return INSTANCE;
    }

    /**
     * Validate license key
     *
     * @param licenseKey The license key string to validate
     * @return A map containing validation results (valid, tech, tier, licenseKey, or reason)
     */
    public Map<String, Object> validate(String licenseKey) {
        // 1. BASIC CHECKS
        if (licenseKey == null || licenseKey.trim().isEmpty()) {
            return fail("Invalid license key format");
        }

        if (!LICENSE_PATTERN.matcher(licenseKey).matches()) {
            return fail("Format mismatch. Got: " + licenseKey);
        }

        // 2. LOAD SECRET
        // First checks environment variables, then falls back to System properties (useful if using Dotenv)
        String secretEnv = System.getenv("PAWAPAY_SDK_LICENSE_SECRET");
        if (secretEnv == null || secretEnv.trim().isEmpty()) {
            secretEnv = System.getProperty("PAWAPAY_SDK_LICENSE_SECRET");
        }
        
        if (secretEnv == null || secretEnv.trim().isEmpty()) {
            return fail("Environment variable PAWAPAY_SDK_LICENSE_SECRET is not set.");
        }

        // 3. DECODE SECRET (Hex Full)
        String secretHexFull;
        try {
            String cleanSecret = secretEnv.trim();
            
            // Fix padding
            int missingPadding = cleanSecret.length() % 4;
            if (missingPadding != 0) {
                StringBuilder padding = new StringBuilder();
                for (int i = 0; i < 4 - missingPadding; i++) {
                    padding.append("=");
                }
                cleanSecret += padding.toString();
            }

            byte[] secretBuffer = Base64.getDecoder().decode(cleanSecret);
            secretHexFull = bytesToHex(secretBuffer).toUpperCase();

        } catch (IllegalArgumentException err) {
            return fail("Failed to decode secret key: " + err.getMessage());
        }

        // 4. EXTRACT SIGNATURE FROM KEY
        String[] parts = licenseKey.split("-");
        String techPrefix = parts[0];
        String tier = parts[1];
        // Combine the last 3 parts to get the signature (e.g., 9EC33F9BC513)
        String providedSignature = (parts[2] + parts[3] + parts[4]).toUpperCase();

        // 5. VERIFY (UPDATED LOGIC)
        // Instead of expected_signature = secret_hex_full[:12], 
        // we check if the signature exists ANYWHERE in the master hex.
        // This supports Key #1, Key #2, and Key #3 generated by the PHP script.
        if (secretHexFull.contains(providedSignature)) {
            // --- SUCCESS ---
            Map<String, Object> result = new HashMap<>();
            result.put("valid", true);
            result.put("tech", techPrefix);
            result.put("tier", tier);
            result.put("licenseKey", licenseKey);
            return result;
        } else {
            // Debugging output (optional, remove in production)
            // LOGGER.debug("[Debug] Secret Hex: {}", secretHexFull);
            // LOGGER.debug("[Debug] Key Sig:    {}", providedSignature);
            return fail("Invalid license signature. Key does not belong to this Secret.");
        }
    }

    /**
     * Helper to standardise failure responses
     */
    private Map<String, Object> fail(String reason) {
        LOGGER.warn("[PawaPay License] {}", reason);
        Map<String, Object> result = new HashMap<>();
        result.put("valid", false);
        result.put("reason", reason);
        return result;
    }

    /**
     * Utility to convert a byte array to a hex string representation
     */
    private String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }
}